global:
    scrape_interval: 3s

scrape_configs:
  - job_name: 'IdentityServiceMetrics'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'Identity Service'
  - job_name: 'DemoMetrics'
    static_configs:
      - targets:
        - demo.promlabs.com:10000
        - demo.promlabs.com:10001
        - demo.promlabs.com:10002